---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  sqlite3
  database: mrc_development.db

# Add more repositories
# repositories:
#   repo1:
#     adapter:  sqlite3
#     database: sample_1_development.db
#   repo2:
#     ...

test:
  <<:       *defaults
  database: mrc_test.db

# repositories:
#   repo1:
#     database: sample_1_test.db

production:
  <<:       *defaults
  database: mrc_production.db

# repositories:
#   repo1:
#     database: sample_production.db

rake:
  <<: *defaults